#pragma once

// Vial & Memory Settings
#define VIAL_KEYBOARD_UID {0x8A, 0xE4, 0xC2, 0x19, 0xF3, 0x7B, 0xD5, 0x41}
#define VIAL_UNLOCK_COMBO_ROWS { 0, 0 }
#define VIAL_UNLOCK_COMBO_COLS { 0, 1 }

#undef DYNAMIC_KEYMAP_LAYER_COUNT
#define DYNAMIC_KEYMAP_LAYER_COUNT 5
#define VIAL_TAP_DANCE_ENTRIES 10
#define VIAL_COMBO_ENTRIES 10
#define DYNAMIC_KEYMAP_MACRO_COUNT 20
#define DYNAMIC_KEYMAP_MACRO_EEPROM_SIZE 500 

// Encoder Settings
#undef ENCODER_A_PINS
#undef ENCODER_B_PINS
#define ENCODERS_PAD_A { D4 } 
#define ENCODERS_PAD_B { D1 }
#define ENCODER_RESOLUTION 4

// Extreme Space Savers
#define NO_ACTION_ONESHOT
