/* SPDX-License-Identifier: GPL-2.0-or-later */

#pragma once

#define VIAL_KEYBOARD_UID {0xB2, 0xD7, 0xBF, 0x79, 0x30, 0x92, 0x05, 0x07}
#define VIAL_UNLOCK_COMBO_ROWS { 0, 0 }
#define VIAL_UNLOCK_COMBO_COLS { 3, 4 }

/* USB Device descriptor parameter */
#define VENDOR_ID       0xDEAF // machineabuse
#define PRODUCT_ID      0x0913 // autogenerated
#define DEVICE_VER      0x0010
#define MANUFACTURER    "imchipwood"
#define PRODUCT         "dumbpad"
#define DESCRIPTION     "dumbpad"

/* Column/Row IO definitions */
#define MATRIX_ROWS 4
#define MATRIX_COLS 5
#define MATRIX_ROW_PINS { F4, F5, F6, F7 }
#define MATRIX_COL_PINS { C6, D7, E6, B4, B5 }
#define UNUSED_PINS

/* Single rotary encoder (Modernized to prevent Redefined errors) */
#undef ENCODER_A_PINS
#undef ENCODER_B_PINS
#define ENCODER_A_PINS { B2 }
#define ENCODER_B_PINS { D4 }
#define VIAL_ENCODER_DEFAULT { KC_VOLD, KC_VOLU, KC_TRNS, KC_TRNS, KC_LEFT, KC_RGHT, KC_DOWN, KC_UP }

/* Onboard LEDs  */
#define LED_00 B6
#define LED_01 B1
#define LED_02 B3

/* Bootmagic (Modernized to prevent Redefined errors) */
#undef BOOTMAGIC_ROW
#undef BOOTMAGIC_COLUMN
#define BOOTMAGIC_ROW 3
#define BOOTMAGIC_COLUMN 0
