VIA_ENABLE = yes
VIAL_ENABLE = yes
ENCODER_ENABLE = yes
TAP_DANCE_ENABLE = yes
COMBO_ENABLE = yes

# Aggressive space-saving measures
LTO_ENABLE = yes
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
