name: Build Dumbpad Vial
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/qmk/qmk_cli:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build Firmware
        run: |
          git config --global --add safe.directory $(pwd)
          qmk compile -kb dumbpad/v1x_dualencoder -km vial

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dumbpad-vial-firmware
          path: .build/*.hex
